// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_7dE6vNNgkUsyrCePNtLUUFshhMvIC_o',
    appId: '1:600608345420:web:f1c32d8de60f6c59e553e9',
    messagingSenderId: '600608345420',
    projectId: 'parking-bf109',
    authDomain: 'parking-bf109.firebaseapp.com',
    storageBucket: 'parking-bf109.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbeynbcJWi30Wbk6RkIiwvbOiO7EJZjNk',
    appId: '1:600608345420:android:3b433f17b881e2a5e553e9',
    messagingSenderId: '600608345420',
    projectId: 'parking-bf109',
    storageBucket: 'parking-bf109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm60aznvZDOOyTAgrSvfDQyeP0lxdORLA',
    appId: '1:600608345420:ios:cc8f4bfc3a04fe48e553e9',
    messagingSenderId: '600608345420',
    projectId: 'parking-bf109',
    storageBucket: 'parking-bf109.firebasestorage.app',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm60aznvZDOOyTAgrSvfDQyeP0lxdORLA',
    appId: '1:600608345420:ios:cc8f4bfc3a04fe48e553e9',
    messagingSenderId: '600608345420',
    projectId: 'parking-bf109',
    storageBucket: 'parking-bf109.firebasestorage.app',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_7dE6vNNgkUsyrCePNtLUUFshhMvIC_o',
    appId: '1:600608345420:web:9c5fea291fe4b52be553e9',
    messagingSenderId: '600608345420',
    projectId: 'parking-bf109',
    authDomain: 'parking-bf109.firebaseapp.com',
    storageBucket: 'parking-bf109.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA_7dE6vNNgkUsyrCePNtLUUFshhMvIC_o',
    appId: '1:600608345420:web:f1c32d8de60f6c59e553e9',
    messagingSenderId: '600608345420',
    projectId: 'parking-bf109',
    authDomain: 'parking-bf109.firebaseapp.com',
    storageBucket: 'parking-bf109.firebasestorage.app',
  );

}
